# Generated by Django 2.2.6 on 2019-10-19 00:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingCamera',
            fields=[
                ('camera_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Camera')),
                ('spots', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=4), size=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.camera',),
        ),
    ]
