# Generated by Django 2.2.6 on 2019-10-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingcamera',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
