# Generated by Django 2.2.6 on 2019-11-02 15:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PederastianCamera_reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_people', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='PederastianCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_zone', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=4)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.Camera')),
            ],
        ),
    ]
